BROKER_URI=
BROKER_URI2=
BROKER_URI3=

TIMEOUT_SECONDS=500
BATCH_SIZE=2048

LOAD_TOPIC=
ROUTE_TOPIC=
FACILITY_TOPIC=

SEARCH_URI=
SEARCH_USER=
SEARCH_PASS=
SEARCH_INDEX=

ROUTE_API_URI=
ROUTE_API_TOKEN=

FAAS_API_URI=
FAAS_API_TOKEN=

FACILITY_TIMINGS_FILE=
