visitors = {
    "TSP": {
        "t_vertex_v_g",
    },
    "CoreNumbers": {
        "examine_vertex_v_g",
        "finish_vertex_v_g",
        "examine_edge_e_g",
    },
    "MaximumAdjacency": {
        "initialize_vertex_v_g",
        "start_vertex_v_g",
        "examine_edge_e_g",
        "finish_vertex_v_g",
    },
    "BellmanFord": {
        "examine_edge_e_g",
        "edge_relaxed_e_g",
        "edge_not_relaxed_e_g",
        "edge_minimized_e_g",
        "edge_not_minimized_e_g",
    },
    "Dijkstra": {
        "initialize_vertex_v_g",
        "discover_vertex_v_g",
        "edge_not_relaxed_e_g",
        "edge_relaxed_e_g",
        "examine_edge_e_g",
        "examine_vertex_v_g",
        "finish_vertex_v_g",
    },
    "AStar": {
        "initialize_vertex_v_g",
        "discover_vertex_v_g",
        "examine_vertex_v_g",
        "examine_edge_e_g",
        "edge_relaxed_e_g",
        "edge_not_relaxed_e_g",
        "black_target_e_g",
        "finish_vertex_v_g",
    },
    "DFS": {
        "initialize_vertex_v_g",
        "start_vertex_v_g",
        "discover_vertex_v_g",
        "examine_edge_e_g",
        "tree_edge_e_g",
        "back_edge_e_g",
        "forward_or_cross_edge_e_g",
        "finish_vertex_v_g",
    },
    "BFS": {
        "initialize_vertex_v_g",
        "discover_vertex_v_g",
        "examine_edge_e_g",
        "examine_vertex_v_g",
        "tree_edge_e_g",
        "non_tree_edge_e_g",
        "gray_target_e_g",
        "black_target_e_g",
        "finish_vertex_v_g",
    },
    "NeighborBFS": {
        "initialize_vertex_v_g",
        "discover_vertex_v_g",
        "examine_vertex_v_g",
        "examine_out_edge_e_g",
        "examine_in_edge_e_g",
        "tree_out_edge_e_g",
        "tree_in_edge_e_g",
        "non_tree_out_edge_e_g",
        "non_tree_in_edge_e_g",
        "gray_target_e_g",
        "black_target_e_g",
        "gray_source_e_g",
        "black_source_e_g",
        "finish_vertex_v_g",
    },
}
